### PR TITLE
prevent scanning interfaces and traits

### PR DESCRIPTION
**Pull request by mbolli**
juliangut/mapping tries to make `new ReflectionClass($sourceClass)` of whatever is returned by `loadClassFromFile()`. If there is an interface or a trait in the list of files, `$sourceClass` will be just the namespace (`\T_CLASS` not found) and so an exception is thrown. 

I was thinking about 

- either catching the exception (but then what to do with it)
- adding a `class_exists()` check (this would autoload the class or be potentially wrong)

### CODE REVIEW

**Comment by juliangut** [comment]
Great spot!

I've made some tests and seen there can be some false positives identifying class names when using traits, such:

 ```php
namespace Attribute

trait Example
{
    public function aaa(): void
    {
        $var = new class() {};
    }

    public function ccc(): void
    {
    }
}
```

`ReflectionException: Class "Attribute\ccc" does not exist`

`loadClassFromFile` method should firstly try to find "interface" or "trait" in order to completely ignore the file and only then fall back to returning empty string (instead of null) in case no class name is found

I haven't tried all possible combinations, there are only so many ways you can include "class" token in a file, in most cases it'll render the file invalid

Could you introduce interface/trait detection before class in this PR?

**Comment by mbolli** [comment]
Thanks for the feedback.

Returning an empty string would be possible, but is not compatible with `class-string<object>`. There is no `empty-string` type, so `string|class-string<object>` would be needed. This makes a type-cast to `class-string<object>` in front of `new ReflectionClass()` necessary. That's your decision.

Another thing, right now the cyclomatic complexity of the method is too high with 11/10. I don't see any way to reduce this without splitting the method in two parts, although not sure which ones make sense.

**Comment by juliangut** [comment]
You're right on the empty-string|null so lets go on with it

About reducing cyclomatic complexity I see two things that can be done, firstly extract $validTokenTypes discovery into a private method, then make findNextToken accept not one type but an array so the interface/trait detection gets reduced to one condition only, presumably complexity in findNextToken won't be raised too much

**Comment by mbolli** [comment]
Yes, that was it!

**Pull request merged**
